# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "V0qp0nouWZ/l6AWmZPfHvRihlXrbN/z5SMl+wzynBw99vXDu4IhRFebfD3/4dcr9bg15DPYOGxVMlSuwHcAdDJIBjDFEeFRS3Nvponoyw+YGrdpGdbB1oI5BEkHWwSueiuVCosZO8eB6dTheIzfArxqZ4NWgTocxTh1DxGrOcFBBwI84e1+12ANiQqBmlFrWoAlYCpQ7hXEOfar6dqWv4a1PrevwxjLHYLoPPy0ydPG4Jd7+yZKEgb7yjJc3IGIduDl8Xg6DgHzTf8efpRCaq4b+Foed2gdnELEsBRgbhcT9ZpJORQ7g0EeQgi7ebtu/GuzhPiX5fQH4/8Y4GEB7u3YOTKjQjpL2/XMtDjHWJHbWPBZOTytKMnKbtqfD+irLYrzB8YicC2GC56Cvj4bYWbJQVUHp3gd2hOeoAUPcFgMm8B1/iLS3sxVpsDC88hBKr6WPpXap8uO8XE91dZpu08/hM8xZnJJGXTd3phN5Bl72WZtAsw587pfmIBuLxlezO8xG9zFmLhNG8ZAyVE6X7y4tLrtxq6ipAnyvQOeK/4NPzETmhyGNSd17+kSI9Tu1bBY+/g8y20dvKZBgTJ/ZuRyNThy2m8pOalrawwObgZkU78DFmxeOEZyspy+LPedLFwaS0XKPiMCSKTu1RrBFwUBP8LmxH7C1brV7B65Y+Ic="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
