# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "b6039vI0ksUwstDpfSVLTWwMyA3BNCDzzt8JxceLChBsqc0akjwN7Py1oKvkj3uoB3jDUbYp2RZg7wkaRDvuo9rG6ZP8jZsFvXRxnP29gCbTlO14NlKnpfy7SW5DMS36ffIuveIQCxnBdDvuUDAnCd+Dwf6KIZbnlhE0vnW7sU0yIwhu9KB60Ph0EMHmfZyzqE58dpKpymL1dnoZIw6rFOV5HMN1Nc3UsMkxt7x9OyGBKeUAX4CJs8KMc+bsuzM6ukeGex2O9+m1fiGqJIFAy8oqJFqvqZLg5fiAbNL/169jwfMNRYN4qpyY5XJ1IxvtPObJxwyImT59zgDUNs/rsW1mJrIXLvmTckd3AjgIzCdaiJLBHa6ij0ps63F2iBtljDLAEs04BHCu2csJcWZ3d3E0h9n4mmGDSqHWe+1SfPbfpCMSWLqKQvxYT8XDvO9mM0uvEbQWyqGt1IzlcxRe+QcAz3p8yIoY+/DmV9fx/xAyJ0o29TbOUP/pqAaf2eJp+rF28mfwTIm7tiRgkZOM6B3hDjlApqR7yVApiobSS6c3VxnyIfq7fT5dnkh+u3NdxfJ+WUY1YsXCIgSa+kRZCxSXeiNEn001J6FGslKeXC7fT5cktky7clyV96WiEIoG1ZMlnBtH40/2bVZzJfxMPbL03ZjBBj510aCeKK/eixs="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
