# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Bifyth0KYAW1G2xp1TN5biZvBf0Hkux1B4pE9mRu7NsbtPrxSpssffQ/RJoNzm2dB8+4bGKg8DxrOwM7KpJefwTk9taBOI9gTgBXWbz1vX/Y+H6JyOvUknUiyS+PJ0OeLG7LuVDZBepKN2Qy2IUIkR6ZyUUm+1k4VxJ8Jn78Asie5JySXX/VD0gsQsGFLqDbG1r/ZiN4rbS6BmY1/jGyGrPIQFfrJuBVCg5tfJ4cel2ugupyNuYCQ11g3o18zyvrvCTmwxFp3OxfO9cJO07K1eZUrBFEBo/WLa/oaevNbVPX1nDPL8znIpH9Bvj4hoEW6FiygEP26NO/6mM9sxmn8DIpvMMe8xWxnpbf0rjIIMfaKrl5auInN/7U4GYtJdfpBjf5KLKwhPDgRzzIucmdTbs0Qw2Hg6AFDl89m8LEaglqCozW7CdmfFDnn41xu9NKH92+fjNuD6HfGeX0kRfBqUEv6iTEObTkoXusbyzdgffTJ9KMUHK0hWXDfu6beSLCUgmzVPkTGDx/BflU5+XZmlS+4iO63bmdRbr/GzgNmOs3OP9SH2xrqV6GKKZz1T0CXuAvb7H7FS7uAnBv8ogGXwlgWl/55sQil9uUlU6UoYAP4DGKSmziEdOSd9hgxTWPAwVO5A8+vNoU8LBuWl1lLEO5rkrGV/XIRvVDS9EAtZ4="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
