travis:
  secure:
    BINSTAR_TOKEN: Bifyth0KYAW1G2xp1TN5biZvBf0Hkux1B4pE9mRu7NsbtPrxSpssffQ/RJoNzm2dB8+4bGKg8DxrOwM7KpJefwTk9taBOI9gTgBXWbz1vX/Y+H6JyOvUknUiyS+PJ0OeLG7LuVDZBepKN2Qy2IUIkR6ZyUUm+1k4VxJ8Jn78Asie5JySXX/VD0gsQsGFLqDbG1r/ZiN4rbS6BmY1/jGyGrPIQFfrJuBVCg5tfJ4cel2ugupyNuYCQ11g3o18zyvrvCTmwxFp3OxfO9cJO07K1eZUrBFEBo/WLa/oaevNbVPX1nDPL8znIpH9Bvj4hoEW6FiygEP26NO/6mM9sxmn8DIpvMMe8xWxnpbf0rjIIMfaKrl5auInN/7U4GYtJdfpBjf5KLKwhPDgRzzIucmdTbs0Qw2Hg6AFDl89m8LEaglqCozW7CdmfFDnn41xu9NKH92+fjNuD6HfGeX0kRfBqUEv6iTEObTkoXusbyzdgffTJ9KMUHK0hWXDfu6beSLCUgmzVPkTGDx/BflU5+XZmlS+4iO63bmdRbr/GzgNmOs3OP9SH2xrqV6GKKZz1T0CXuAvb7H7FS7uAnBv8ogGXwlgWl/55sQil9uUlU6UoYAP4DGKSmziEdOSd9hgxTWPAwVO5A8+vNoU8LBuWl1lLEO5rkrGV/XIRvVDS9EAtZ4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
