travis:
  secure:
    BINSTAR_TOKEN: lq142+cBTMyRIzKpLPM/nJHfKc6XzuGe+wYmo2iYP4+WMhj5rcLTikKlEsHMm+d4UCgr+h14l1YT4NgCJ4CI3NGDSZHq/nDnI082bY45NM+Hrg1Q9/hIC95yMmwOJUInTDAASrxAz3EjTiV+nKvIYl7kMIf1QbEXyn750tImKleamm++uCsDF6kKfwWkWC0ss4BazfdgiWJorrAVY4SYM/H4TJkDlDIEQTDlTSmXtW4xweRnKf1y4m49x6WDljdmB1sJdw++Ze0VQVa+6B0SrfK28Bv2PGAxufXsdIeY2Qv1MEMKGzj+1ERQU4WpytgeCUEqfOgV+dwT2aC/W924+e6tIxhfEpYpGZDyam8uY9nuJ9sJB+vEJZtAgUjz0YgRx4ODsXgdfy1aQGRji1/iBT4HDQEdRbeOZ1kpni2bcaL4220QiCyExdErl9kxVykp0b/zYGAzJsEvjfnwKQckcR52JcJHMsrq5BqkgasgzhRn+wxxAu5lebo/6G4nh+SB9xxBl38smZ58p1FKD4aXJZxTdrGCS7jdAdfkfhOvQdhkiTXK6OUtHKdWuSenyrtPbfnE1+BUQV0g5wPenxLXwsDYXTzBevDVk8xN09+kI7FpCvjhdW3Qvb8TtkRVi5XM209McUhrGHogjlPcBY6zVk3J54QJOnvqn6p3fs+v6S4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
