travis:
  secure:
    BINSTAR_TOKEN: v+a3E3ra+sexYWHCGVM2z9H/XqsS8J4pmmNvwA/Zs/ub6Vn0nyskKX9TTgYeYbEkDNnG82Fvzoyo7eMbUfkJ1S6jX91qz7Z6xkf6txK0lmWp/eeCLVvD7B7NBvlWP8jgKxej3YT7HsyFjn+xbNSTcbVSyvv+jP8ILzSiqil++W02DAfFfUyYxqpeeV1KmcVn/2UxC27UMUaD7TvK0B4GNMzGAKyGbYP867Vibn2RjX51P+klWQI/Hev1no4k4A2m7pk8w4WPAlJcRyEUR0Yk6kvdq5Nw0Qrsp7XNUUnRuN3Qy08mp6lz8heQNwsZ3jx2/MAq7c6JcYaG6A2FEVLwRUKWfShSCvzKicOGuqnKmGKplj1MFVKPQXcfcsKzSRbEW05GVdovNdC6C9GyMawrTgiGGXiJoTe0VGoIDrfysZ+G/R1rUBkaVGnMPfnjVoa8deA0zpAP7cjiqtTLAP+I+IadNOuhqrEqkEBrr4P6xh31XZ5t7j3kZEEp+k08Ii4xc9R1JADeoi9k69ggFmYKJlBiYq9+MGLi/LvgWYf/u1NsHCkrtRYjbWB/U4a26ScgXyvSBe3NpXivNG3sm9k5KwdIFCYhrCefbLd/iytktvC7SXSeB9HpkAxuwsh3hzlx8EdD29GLE4GR4i3mYVjDAz/ax+ZkhcvibyO+B67Zm7E=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
