travis:
  secure:
    BINSTAR_TOKEN: dCROQlJrWtboddlOVoaLpiBJIO9bJfK6rGjwJqMHi7IOp3dM9xBr8vZ1etITvuLWFm+rwzkK1XnPYZm17jYsaI/91l/iM1TPzfeZ7kV4FcRpl2KnAJfUsDoRQwIDmBWQiRAsC+zey4BYIsSxpKEsqx1GqN+pb8RrR1IdLJ3FL3FpPHOgO0IJh2zWQPMBuJsoOKZu1xrlnqvG/l9Uzezh7ZH3Z4WEZXquwIw4WuJHzEzBLNP0fcaX0lJvtDM1b2hFuwCJBoRgKM+6YODLd1kBqIAxI7WUw7YC+oFU+x3AFj7zjeGpc8u6YAzCKVa5tyHGSRaukARSsKiCfXuuvbS/OxwW131oPLZtQOxQU4HL35qydJrYIN7KqPUKcD81opWykvc2an81rWapft2yxXmDcGSwWRmE1FGO+sHq4aLqXoQlxZk5bfHgeRsZNT+DTBjfvQCgoia6sA8vB7qyIhjIpkxhNaWb5V3eOjar6sOuwaV/wgOTCe/HyLcwaq65Ck0DYgo7FHtKZ5gWts4WeNt9molt3qM913CbgwzSvf/RmNFXH0k/CF+0KWEom2MDim3NFyeNPi8SBRoOVsfRhF6MtM2SBoHcVVWAC5pGoyjch6sIeVFhKZ5p7AqYTj3vYg4ojIk5/aPzogWqVAGfjWdOUa4FoXfVqvv4Yp2psIN2XJM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
