travis:
  secure:
    BINSTAR_TOKEN: lfSVOWZHt5PzpPc1MztXNd+0wuqN4OauhLAic8IqWhA4xeaJV8ribbX7o8LeUtI/b51KwFQ/OdwiMTUAcJfeyaBTyPqt9QNh3siMrKJagPjBbc0yQxuuaBtmO8HuWrDDCifez6u0e2ZjGOvdzWLjsmqGoQw7w0UGem+6Xi/yI2lmEJKVLUjCOgmyE4INx1e+gFQoreFBnSAc3A1n5qenEb0L62ouLiHg217OFhVSkF945D8TxE+fnlfMH9EKZiPeeP6ge8RNBxNA1Q3ZqhhiCA70Pwol+8u5gQblRARvNyueimsgDd0IhybOdWipo1EP+tp36PW8pH1JobbomgGIQz9gqsOJUWHH4mIS4alBclqaN/v/7m1573OellNwtODn5SrFIEGICClfqQrxgZcHblFrEzOTyAQtl1xF+egcIgwHjMfb4y2qOwKEogifLAC9WAFEcNWsgVc3213vt0MkVhNUzzQ2dMTVws2Rtwh+i1pGc7hM/gm2AgE1mor1IBkuKfAiuz+I+ivvFCmrsUJJVgC4lKXkEsulsDrYrZmjQrVv7YfK7NyXe9BxwIYsnnpCUs0N00aLCOpZcIqjtEE1ASuVsA8qo3obFNd7IhMAYAy9GoGd/jC9rhz8CUSlHPwe5vA4IrTBLzDGDsvNIDRf36Fa1IX9nziLOD+hp+ZLrKQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
