travis:
  secure:
    BINSTAR_TOKEN: Lid7tWO26SwjhXFxOzHglHD+R5pj/m+uNVjnztvhLRzqE/gWYy+NtIA2w69pGBUehwkp5+rUKBYpChA8dvlC8+6gpAWpDQ10JXQUdhAjztJKBogTwxRq7ztJ4vgsvdLFOTCihMrkSlENzNt5hKWiaC73225c3EccjDE+0681/VTf40tdH24RFGce3r6qNigRF389WDs972P8cXBNcXnpAmtFdc7IHB0pLgIu2h0FWaNPeflUUDuy5ZTB21cZ7TWW6ktCxZKV5NR6hB86P52Wp627Yiq63NaN6LVktxq0sZDiA8V6LJET5hKqIoNZKZGF0xxJ7i7ILueCle0fMJCC6kzKsBdEPcrAfyh9d9UD8bwvw278VE1Z/klPmA+rYP2bNYteIW9nXxp911ikBVhe7HXSyOsRvS4os/KGUyawCihYUdQmU4HWMive3PWslCXFLoVimLy7Lq7r7LQF+egbmj5G7hcrhpiQ9FD9fti9XdQ8HMRZopvMWzZhnlH8bQJRzXtncGulSY8uY/d9+GG2xeQ1RSwJXzcYjWHs5RI6UCzSKpkmuRzuDuBy2H0juGgpw+55ibADfo0a4bMIdp42L5u01j7N7dtdxpTMy9eV7KsQQVzG8rpD3/LKfJGkJZo3vfIh3Atst2iyT4Is88K83B/K7geCM/0+cWILoy5PO14=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
