travis:
  secure:
    BINSTAR_TOKEN: w2GEtXCq0hj/6NzWSY5a99VFYBQ/ZclmKA7a59wZW+uAOFD8YvNsAp9okQ9WuLWSs8rr1SL4pCGWwBc+u5lZTqp5x4C5vj1iYfDAT+UauIYAlg7daeQnIEmKYbcpiP0kDUU8canL/+QGvnq87DIaWnHlfZqKYwR4CkIzhP0HSVfVzupLNS64ICbCzqoVO6xeuRCVfLpFFXO2Ij7Ioy+Lfibuor1Tons8Kn193b9MSx/XC88GnQPS++3PLMJkSO8yWptpXd+l/n5rYL/c2174sEwKLjzWt4lPETCdmXsWARet/GgGMpiJcE+DDEkQ+e06vnukyWUGwFolhKHTQCGBTOD0fDxSNEhcDg0wIf81+KAlwApmmAZwlNJVB2pqIQGmKnNw2Rgr6IVhVhzbQNww8NGx529sv/ZdgES/IreEChFAGRgAXvfOCEnpOM3XXQzzLY0o/qyOsiG6O3wQPJ54kENiDwRpNTO1Ar0OtDVo/hrKMatEjojrkHvMemFguuG7KlfN1ySUc/pIhV6LzLI/goB+z3aj7AZtdWaa9u7BGM7u4JNZ1r1tjQkjlY+SEF93j3RPoih9w1Or8hlknvj8iFwa62rpY1tqN4NwyQBUj46XkooJA0nsQ7pXdeDLyciDNSgwZGu1dCh/6DZ4lxiMFd/CnSDSPua9wthM2+zkG0E=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
