travis:
  secure:
    BINSTAR_TOKEN: V0qp0nouWZ/l6AWmZPfHvRihlXrbN/z5SMl+wzynBw99vXDu4IhRFebfD3/4dcr9bg15DPYOGxVMlSuwHcAdDJIBjDFEeFRS3Nvponoyw+YGrdpGdbB1oI5BEkHWwSueiuVCosZO8eB6dTheIzfArxqZ4NWgTocxTh1DxGrOcFBBwI84e1+12ANiQqBmlFrWoAlYCpQ7hXEOfar6dqWv4a1PrevwxjLHYLoPPy0ydPG4Jd7+yZKEgb7yjJc3IGIduDl8Xg6DgHzTf8efpRCaq4b+Foed2gdnELEsBRgbhcT9ZpJORQ7g0EeQgi7ebtu/GuzhPiX5fQH4/8Y4GEB7u3YOTKjQjpL2/XMtDjHWJHbWPBZOTytKMnKbtqfD+irLYrzB8YicC2GC56Cvj4bYWbJQVUHp3gd2hOeoAUPcFgMm8B1/iLS3sxVpsDC88hBKr6WPpXap8uO8XE91dZpu08/hM8xZnJJGXTd3phN5Bl72WZtAsw587pfmIBuLxlezO8xG9zFmLhNG8ZAyVE6X7y4tLrtxq6ipAnyvQOeK/4NPzETmhyGNSd17+kSI9Tu1bBY+/g8y20dvKZBgTJ/ZuRyNThy2m8pOalrawwObgZkU78DFmxeOEZyspy+LPedLFwaS0XKPiMCSKTu1RrBFwUBP8LmxH7C1brV7B65Y+Ic=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
