travis:
  secure:
    BINSTAR_TOKEN: b6039vI0ksUwstDpfSVLTWwMyA3BNCDzzt8JxceLChBsqc0akjwN7Py1oKvkj3uoB3jDUbYp2RZg7wkaRDvuo9rG6ZP8jZsFvXRxnP29gCbTlO14NlKnpfy7SW5DMS36ffIuveIQCxnBdDvuUDAnCd+Dwf6KIZbnlhE0vnW7sU0yIwhu9KB60Ph0EMHmfZyzqE58dpKpymL1dnoZIw6rFOV5HMN1Nc3UsMkxt7x9OyGBKeUAX4CJs8KMc+bsuzM6ukeGex2O9+m1fiGqJIFAy8oqJFqvqZLg5fiAbNL/169jwfMNRYN4qpyY5XJ1IxvtPObJxwyImT59zgDUNs/rsW1mJrIXLvmTckd3AjgIzCdaiJLBHa6ij0ps63F2iBtljDLAEs04BHCu2csJcWZ3d3E0h9n4mmGDSqHWe+1SfPbfpCMSWLqKQvxYT8XDvO9mM0uvEbQWyqGt1IzlcxRe+QcAz3p8yIoY+/DmV9fx/xAyJ0o29TbOUP/pqAaf2eJp+rF28mfwTIm7tiRgkZOM6B3hDjlApqR7yVApiobSS6c3VxnyIfq7fT5dnkh+u3NdxfJ+WUY1YsXCIgSa+kRZCxSXeiNEn001J6FGslKeXC7fT5cktky7clyV96WiEIoG1ZMlnBtH40/2bVZzJfxMPbL03ZjBBj510aCeKK/eixs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
